name: Trigger Event Workflow

on:
  workflow_dispatch:
    inputs:
      message:
        description: "Message to send to another repository workflow"
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger Workflow"
        id: trigger_request
        run: |
          curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/haydenk/symmetrical-couscous/dispatches \
              -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"message\": \"${{ github.event.inputs.message }}\", \"unit\": false, \"integration\": true}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.trigger_request.outputs.data }}'"
